"""empty message

Revision ID: 7ab7c15f11a3
Revises: e55c3485a26f
Create Date: 2024-06-15 22:00:44.672132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab7c15f11a3'
down_revision = 'e55c3485a26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reddit_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qa_model_available', sa.Boolean(), nullable=True))
        batch_op.drop_column('qa_model_abailable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reddit_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qa_model_abailable', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('qa_model_available')

    # ### end Alembic commands ###
