"""empty message

Revision ID: c9fe54db7d6b
Revises: 
Create Date: 2024-06-09 16:59:51.285052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fe54db7d6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('num_submissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('topic_distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=30), nullable=False),
    sa.Column('distribution', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['reddit_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=30), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['reddit_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_sentiment')
    op.drop_table('topic_distribution')
    op.drop_table('reddit_user')
    # ### end Alembic commands ###
