"""empty message

Revision ID: e55c3485a26f
Revises: e780412ae363
Create Date: 2024-06-15 21:58:33.312679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55c3485a26f'
down_revision = 'e780412ae363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reddit_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qa_model_abailable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reddit_user', schema=None) as batch_op:
        batch_op.drop_column('qa_model_abailable')

    # ### end Alembic commands ###
