"""empty message

Revision ID: e780412ae363
Revises: c9fe54db7d6b
Create Date: 2024-06-12 17:34:01.454494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e780412ae363'
down_revision = 'c9fe54db7d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reddit_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_sentiment', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reddit_user', schema=None) as batch_op:
        batch_op.drop_column('average_sentiment')

    # ### end Alembic commands ###
